spring:
  application:
    name: portfolio-service
  security:
    oauth2:
     client:
        registration:
          portfolio-service:
            provider: keycloak
            client-id: portfolio-service
            client-secret: 6a38eaf5-dff2-413b-b4cc-ed9b89969304
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/auth/realms/CryptoInc
     resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/CryptoInc
           
server:
   port: 8180

logging:
  level:
    root: INFO
    com.memorynotfound: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO